In [6]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [21]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr[0,1])
print(arr[1,-1])
print(arr[-1,0])
print(arr.shape)
for x in arr:
    for y in x:
        print(y)

[[1 2 3 4]
 [5 6 7 8]]
2
8
5
(2, 4)
1
2
3
4
5
6
7
8


In [27]:
arr=np.array([1,2,3,4])
for x in arr:
    print(x)   

1
2
3
4


In [29]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6 7 8]


In [46]:
arr1=np.array([[1,2,5],[3,4,7]])
arr2=np.array([[5,6,9],[7,8,5]])
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[1 2 5]
 [3 4 7]
 [5 6 9]
 [7 8 5]]


In [245]:
arr1=np.array([4,5,6,7])
arr2=np.array([6,7,8,9])
arr3=np.concatenate((arr1,arr2))
arr4=np.sort(arr3)
print(arr4)

[4 5 6 6 7 7 8 9]


In [247]:
import numpy as np
x=random.randint(100)
print(x)

73


In [173]:
from numpy import random
x=random.randint(100)
print(x)

38


In [195]:
x=random.rand(3,5)
print(x)

[[0.55189403 0.77787212 0.1270592  0.34364888 0.8410495 ]
 [0.38660357 0.66462262 0.60775006 0.16774696 0.5043319 ]
 [0.89850134 0.20829635 0.81426187 0.31061117 0.97005152]]


In [210]:
x=random.rand()
print(x)

0.16021597932669707


In [240]:
x=random.randint(100,size=(4,5))
print(x)

[[19 94 70 15 67]
 [40 38 66 65 25]
 [93 96 47 23  3]
 [16 22 92 66 52]]


In [242]:
x=random.rand(20)
print(x)

[0.75345999 0.08873387 0.85956884 0.80983214 0.18866064 0.47379787
 0.23535489 0.74534809 0.01708907 0.61189905 0.10682591 0.8696328
 0.17629744 0.44052047 0.32245402 0.19530659 0.13602895 0.56003799
 0.78903717 0.89415265]


In [244]:
import numpy as np
arr=np.array([1,2,2,3])
arr1=arr.reshape(2,2)
print(arr1)

[[1 2]
 [2 3]]


In [29]:
import numpy as np
arr=np.array([[1,2,3,4,6],[5,6,7,8,9],[9,10,11,12,13]])
print(arr[:2,:3]) # starts from the 0th row and ends with the 2nd column (contains all elements between them)
print()
print(arr[:3,::2])# here the ::2 is used to skip places 
print()
print(arr[::-1,::-1])
print()
print(arr[:,0])
print()
print(arr[0,:])
print()
print(arr[0])
print()
print(arr[:,:])


[[1 2 3]
 [5 6 7]]

[[ 1  3  6]
 [ 5  7  9]
 [ 9 11 13]]

[[13 12 11 10  9]
 [ 9  8  7  6  5]
 [ 6  4  3  2  1]]

[1 5 9]

[1 2 3 4 6]

[1 2 3 4 6]

[[ 1  2  3  4  6]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]
